apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-lqaa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/gmccarth-tenant/redhat-summit-recap/devfile-sample-code-with-quarkus-lqaa@sha256:6938fd397e81dddd3576e80da9c918d0fe4a03a1fb68f1f9c9bc22971aac8a6c
        name: my-java-quarkus
        resources: {}
status: {}
